metadata:
  labels:
    app: {{name}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{service_port}}
      targetPort: {{internal_port}}
      protocol: TCP
  selector:
    app: {{name}}
