metadata:
  labels:
    app: reclis
    env: {{env}}
    cust: {{reclis_customer}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{service_port}}
      targetPort: {{internal_port}}
      protocol: TCP
    - name: metrics
      port: 9568
      protocol: TCP
  selector:
    app: reclis
    cust: {{reclis_customer}}
