metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      Include /etc/nginx/owasp-modsecurity-crs/nginx-modsecurity.conf
      SecRule REQUEST_HEADERS:User-Agent "test-scanner" "log,deny,id:107,status:403,msg:\'Test Scanner Identified\'"
      SecRuleEngine DetectionOnly
      SecAuditEngine RelevantOnly
      SecAuditLogParts AFHZ
      SecAuditLog /dev/stderr
      SecAuditLogFormat JSON
spec:
  tls:
  - hosts:
    - {{hostname}}
    secretName: docs-certs
  rules:
  - host: {{hostname}}
    http:
      paths:
      - path: /
        backend:
          serviceName: "docs"
          servicePort: 80

