metadata:
  labels:
    app: nowodski
    env: {{env}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{service_port}}
      targetPort: {{nowodski_internal_port}}
      protocol: TCP
    - name: metrics
      port: 9568
      protocol: TCP
  selector:
    app: {{name}}
