spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  {% if loadbalancer_ip %}
  loadBalancerIP: {{loadbalancer_ip}}
  {% endif %}
  ports:
  - name: mqtt-ssl-corp-fw
    port: 443
    targetPort: 8883
  - name: mqtt-ssl
    port: 8883
    targetPort: 8883
  selector:
    app: {{app}}
