metadata:
  labels:
    app: reflow
    env: {{env}}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
    - name: metrics
      port: 9568
      protocol: TCP
  selector:
    app: reflow
