apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: alertmanager
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
  selector:
    alertmanager: alertmanager
