apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
      - name: alertmanager-operated
        namespace: monitoring
        port: web
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  # baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  retention: {{retention}}
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector:
    any: true
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  # version: v2.3.2
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{storage_class}}
        resources:
          requests:
            storage: 64Gi
