metadata:
  labels:
    app: ingress-nginx
  annotations:
    metallb.universe.tf/address-pool: public
  name: ingress-nginx
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: ingress-nginx
  type: LoadBalancer
  {% if loadbalancer_ip %}
  loadBalancerIP: {{loadbalancer_ip}}
  {% endif %}
