apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ingress-nginx
  name: ingress-nginx
spec:
  endpoints:
  - interval: 30s
    port: monitor
    scheme: http
  jobLabel: nginx-ingress
  namespaceSelector:
    matchNames:
    - {{namespace}}
  selector:
    matchLabels:
      app: ingress-nginx-monitoring
