apiVersion: monitoring.coreos.com/v1
metadata:
  name: vernemq
  labels:
    app: vernemq
spec:
  endpoints:
    - interval: 30s
      port: metrics
  jobLabel: k8s-app
  targetLabels:
    - env
    - proj
    - app
    - cust
  selector:
    matchLabels:
      app: vernemq
