metadata:
  labels:
    app: {{ name }}
    cust: all
    env: {{ env }}
    proj: reifenhaeuser
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: ws
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: {{name}}
  type: ClusterIP
