data:
  vernemq.conf.local: |
    {%- if env == 'stage' %}
    accept_eula = yes
    {%- endif %}
    allow_anonymous = on
    allow_multiple_sessions = off
    allow_publish_during_netsplit = off
    allow_register_during_netsplit = off
    allow_subscribe_during_netsplit = off
    allow_unsubscribe_during_netsplit = off
    distributed_cookie = rfhgcxdcookie
    erlang.async_threads = 64
    erlang.distribution.port_range.minimum = 9100
    erlang.distribution.port_range.maximum = 9109
    erlang.max_ports = 262144
    graphite_enabled = off
    graphite_host = localhost
    graphite_interval = 20000
    graphite_port = 2003
    leveldb.maximum_memory.percent = 70
    listener.http.default = 127.0.0.1:8888
    listener.http.metrics = 0.0.0.0:9999
    listener.max_connections = 10000
    listener.mountpoint = off
    listener.nr_of_acceptors = 10
    listener.tcp.default = 0.0.0.0:1883
    listener.vmq.clustering = ###IPADDRESS###:44053
    listener.ws.default = 0.0.0.0:8080
    log.console = console
    log.console.level = info
    log.console.file = /var/log/vernemq/console.log
    log.error.file = /var/log/vernemq/error.log
    log.syslog = off
    log.crash = on
    log.crash.file = /var/log/vernemq/crash.log
    log.crash.maximum_message_size = 64KB
    log.crash.size = 10MB
    log.crash.rotation = $D0
    log.crash.rotation.keep = 5
    max_inflight_messages = 20
    max_offline_messages = 1000
    max_online_messages = 1000
    message_size_limit = 0
    plugins.logger_plugin = on
    plugins.logger_plugin.path = /vernemq/plugins/rh
    plugins.logger_plugin.priority = 52
    plugins.rh_auth_plugin = on
    plugins.rh_auth_plugin.path = /vernemq/plugins/rh
    plugins.rh_auth_plugin.priority = 53
    plugins.vmq_passwd = off
    plugins.vmq_acl = on
    plugins.vmq_diversity = off
    plugins.vmq_webhooks = off
    plugins.vmq_bridge = off
    shared_subscription_policy = prefer_local
    systree_enabled = on
    systree_interval = 20000
    upgrade_outgoing_qos = off
    vmq_acl.acl_file = /vernemq/etc/vmq.acl
    vmq_acl.acl_reload_interval = 10
    vmq_diversity.script_dir = /usr/share/vernemq/lua
    vmq_diversity.auth_postgres.enabled = off
    vmq_diversity.auth_mysql.enabled = off
    vmq_diversity.auth_mongodb.enabled = off
    vmq_diversity.auth_redis.enabled = off
    vmq_passwd.password_file = /vernemq/etc/vmq.passwd
    vmq_passwd.password_reload_interval = 10
