metadata:
  labels:
    app: cert-manager
rules:
- apiGroups:
  - certmanager.k8s.io
  resources:
  - issuers
  - issuers/status
  verbs:
  - update
- apiGroups:
  - certmanager.k8s.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
