apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9101
    targetPort: http
  selector:
    app: node-exporter
