spec:
  replicas: {{replicas}}
  template:
    metadata:
      name: {{name}}
      labels:
        app: "{{name}}"
        env: "{{env}}"
        proj: "reifenhaeuser"
        cust: "all"
        dbconn: "postgres"
        sentry: "dus"
        mail: "mailjet"
    spec:
      containers:
      - name: {{name}}
        image: {{registry_host}}/{{registry_image}}:{{registry_version}}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /api/status/liveness
            port: 4000
          timeoutSeconds: 5
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: "512m"
            memory: "256Mi"
          requests:
            cpu: "128m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/status/readiness
            port: 4000
          timeoutSeconds: 3
          initialDelaySeconds: 5
        env:
          - name: KEYCLOAK_ADMIN_USERNAME
            value: "{{keycloak_admin_user}}"
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{bw_password_container}}
                key: {{keycloak_admin_pass}}
          - name: KEYCLOAK_CLIENT_ID
            value: {{keycloak_clientname}}
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{bw_password_container}}
                key: {{keycloak_clientsecret}}
          - name: POSTGRES_USER
            value: {{postgres_user}}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{bw_password_container}}
                key: {{postgres_pass}}
          - name: POSTGRES_DB
            value: {{postgres_db}}
          - name: POSTGRES_HOST
            value: {{postgres_host}}
          - name: KEYCLOAK_REALM
            value: "{{keycloak_realm}}"
          - name: KEYCLOAK_SESSION_LIMIT
            value: "{{keycloak_session_limit}}"
          - name: KEYCLOAK_EXTERNAL_HOST
            value: "{{keycloak_external_host}}"
          - name: KEYCLOAK_INTERNAL_HOST
            value: "{{keycloak_internal_host}}"
          - name: RESA_HOST
            value: "{{riot_host}}"
          - name: RESA_PORT
            value: "4000"
          - name: RESA_INTERNAL_PORT
            value: "8080"
          - name: RESA_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: {{bw_password_container}}
                key: {{riot_secret_key}}
          - name: MAILER_DEFAULT_FROM
            value: "{{mail_from}}"
          - name: MAILER_DEFAULT_SUBJECT
            value: "{{mail_subject}}"
          - name: REPLACE_OS_VARS
            value: "{{replace_os_vars}}"
          - name: MQTT_HOST
            value: "{{mqtt_host}}"
          - name: MQTT_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {% if mqtt_user != "" and mqtt_user != None %}
          - name: MQTT_USERNAME
            value: "{{mqtt_user}}"
          - name: MQTT_PASSWORD
            value: "{{mqtt_pass}}"
          {% endif %}
          - name: MQTT_PORT
            value: "{{mqtt_port}}"
          - name: SENTRY_DSN
            value: "{{sentry_dsn}}"
          - name: SENTRY_FRONTEND_DSN
            value: "{{sentry_frontend_dsn}}"
          - name: REDIS_HOSTNAME
            value: "{{redis_hostname}}"
          - name: REDIS_PORT
            value: "{{redis_port}}"
          - name: ENV
            value: "{{env}}"
{% if registry_secret is defined and registry_secret %}
      imagePullSecrets:
      - name: {{registry_secret}}
{% endif %}
