apiVersion: monitoring.coreos.com/v1
metadata:
  name: riot
  labels:
    app: riot
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: metrics
    scheme: http
  podTargetLabels:
    - cust
    - proj
    - app
    - env
  jobLabel: riot
  namespaceSelector:
    matchNames:
    - {{namespace}}
  selector:
    matchLabels:
      app: riot
